exports.responseMessageCode = {
    NOT_ALLOWED                                                               : "NOT_ALLOWED",
    EMAIL_EXIST                                                               : "EMAIL_EXIST",
    EMAIL_PASSWORD_REQUIRED                                                   : "EMAIL_PASSWORD_REQUIRED",
    EMAIL_OR_PASSWORD_WROGN                                                   : "EMAIL_OR_PASSWORD_WROGN",
    PARAMETER_MISSING_OR_WRONG_PARAMETER                                      : "PARAMETER_MISSING_OR_WRONG_PARAMETER ",
    SUCCESS                                                                   : "SUCCESS",
    ACCOUNT_CREATED                                                           : "ACCOUNT_CREATED",
    NOT_LOGGED_IN                                                             : "NOT_LOGGED_IN",
    USER_DOES_NOT_EXIST                                                       : "USER_DOES_NOT_EXIST",
    UPLOAD_ERROR                                                              : 'UPLOAD_ERROR',
    NOT_IMAGE                                                                 : 'NOT_IMAGE',
    CANT_FIND_URL                                                             : 'CANT_FIND_URL',
    UPLOAD_SUCCESSFUL                                                         : 'UPLOAD_SUCCESSFUL',
    SESSION_EXPIRED                                                           : 'SESSION_EXPIRED',
    NOT_UPDATED                                                               : 'NOT_UPDATED',
    UNAUTHORIZED                                                              : 'UNAUTHORIZED',
    LESS_QUANTITY_LEFT                                                        : 'LESS_QUANTITY_LEFT',
    WRONG_ORDER_ID                                                            : 'WRONG_ORDER_ID',
    CANNOT_PLACE_ORDER                                                        : 'CANNOT_PLACE_ORDER',
    USER_NOT_FOUND                                                            : 'USER_NOT_FOUND'
  };